export let lang = {
    ru : {
        startText: 'Выберите что надо делать',
        settingText: 'Что желаете настроить?',
        currency: 'Валюты',
        setting: 'Настройка',
        back: 'Назад',
        language: 'Язык',
        notification: 'Уведомление',
        changeLang: 'Выберите язык',
        langChanged: 'Язык изменен на русский',
        news: 'Новости',
        ATMs: 'Банкоматы',
        branchBank: 'Отделение',
        selectCurrency: 'Выберите валюту',
        ATMList: 'Список банкоматов',
        ATMNearby: 'Банкомат поблизости',
        selectBank: 'Выберите банк',
        HalykBank: 'Народный Банк',
        ForteBank: 'Форте Банк',
        TsesnaBank: 'Цесна Банк',
        Kaspi: 'Каспи Банк',
        Kazkom: 'Казкоммерцбанк',
        Sberbank: 'Сбер Банк',
        Eubank: 'Евразийский банк',
        sendLocationMsg: 'Отправить местоположение',
        creditCalculator: 'Кредитный калькулятор',
        depositCalculator: 'Депозитный калькулятор'
    },
    kz : {
        startText: 'Не істегіңіз келеді',
        settingText: 'Cіз нені баптағыңыз келеді?',
        currency: 'Валюта',
        setting: 'Баптау',
        back: 'Артқа',
        language: 'Тіл',
        notification: 'Хабарлама',
        changeLang: 'Тілді таңдаңыз',
        langChanged: 'Қазақ тіліне өзгертілді',
        news: 'Жаңалықтар',
        ATMs: 'Банкоматтар',
        branchBank: 'Банк бөлімшелері',
        selectCurrency: 'Валютаны таңдаңыз',
        ATMList: 'Банкоматтар тізімі',
        ATMNearby: 'Жақын жердегі банкомат',
        selectBank: 'Банкті таңдаңыз',
        HalykBank: 'Халық банк',
        ForteBank: 'Форте банк',
        TsesnaBank: 'Цесна банк',
        Kaspi: 'Каспи банк',
        Kazkom: 'Казкоммерцбанк',
        Sberbank: 'Сбербанк',
        Eubank: 'Еуразиялық банк',
        sendLocationMsg: 'Орналасқан жерді жіберу',
        creditCalculator: 'Несие калькуляторы',
        depositCalculator: 'Депозиттік калькулятор'
    },
    en : {
        startText: 'Choose what to do',
        settingText: 'What do you want to set up?',
        currency: 'Currency',
        setting: 'Settings',
        back: 'Back',
        language: 'Language',
        notification: 'Notification',
        changeLang: 'Choose language',
        langChanged: 'Changed to English',
        news: 'News',
        ATMs: 'ATMs',
        branchBank: 'Branch to bank',
        selectCurrency: 'Select currency',
        ATMList: 'List of ATMs',
        ATMNearby: 'ATM nearby',
        selectBank: 'Select Bank',
        HalykBank: 'HalykBank',
        ForteBank: 'ForteBank',
        TsesnaBank: 'Tsesnabank',
        Kaspi: 'Kaspi bank',
        Kazkom: 'Qazkom',
        Sberbank: 'Sberbank',
        Eubank: 'Eurasian Bank',
        sendLocationMsg: 'Send location',
        creditCalculator: 'Credit calculator',
        depositCalculator: 'Deposit calculator'
    }
};
